// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using wpf_projeto_integrador.Data;

#nullable disable

namespace wpf_projeto_integrador.Migrations
{
    [DbContext(typeof(MusicStationContext))]
    [Migration("20260711221831_ConstraintProfissionalEEmpresa")]
    partial class ConstraintProfissionalEEmpresa
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("wpf_projeto_integrador.Models.Avaliacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<string>("Comentario")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("DataAvaliacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("Nota")
                        .HasColumnType("int");

                    b.Property<int>("ServicoPedidoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("ServicoPedidoId")
                        .IsUnique();

                    b.ToTable("Avaliacoes", null, t =>
                        {
                            t.HasCheckConstraint("CK_Avaliacao_Nota", "[Nota] BETWEEN 1 AND 5");
                        });
                });

            modelBuilder.Entity("wpf_projeto_integrador.Models.CategoriaPagamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("CategoriasPagamento");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Serviço"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Locação"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Venda"
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Multa"
                        },
                        new
                        {
                            Id = 5,
                            Nome = "Outro"
                        });
                });

            modelBuilder.Entity("wpf_projeto_integrador.Models.Chat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<int>("Usuario1Id")
                        .HasColumnType("int");

                    b.Property<int>("Usuario2Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Usuario1Id");

                    b.HasIndex("Usuario2Id");

                    b.ToTable("Chats");
                });

            modelBuilder.Entity("wpf_projeto_integrador.Models.FormaPagamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("FormasPagamento");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Pix"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Cartão de Crédito"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Cartão de Débito"
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Dinheiro"
                        },
                        new
                        {
                            Id = 5,
                            Nome = "Boleto"
                        },
                        new
                        {
                            Id = 6,
                            Nome = "Transferência Bancária"
                        });
                });

            modelBuilder.Entity("wpf_projeto_integrador.Models.LogSistema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataHora")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("EntidadeAfetada")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("EntidadeId")
                        .HasColumnType("int");

                    b.Property<string>("Erro")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("NomeComputador")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Sucesso")
                        .HasColumnType("bit");

                    b.Property<string>("Tela")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TipoAcao")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("LogsSistema");
                });

            modelBuilder.Entity("wpf_projeto_integrador.Models.Mensagem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChatId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataEnvio")
                        .HasColumnType("datetime2");

                    b.Property<int>("RemetenteId")
                        .HasColumnType("int");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("Visualizada")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ChatId");

                    b.HasIndex("RemetenteId");

                    b.ToTable("Mensagens");
                });

            modelBuilder.Entity("wpf_projeto_integrador.Models.Pagamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaPagamentoId")
                        .HasColumnType("int");

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataPagamento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataVencimento")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<int>("FormaPagamentoId")
                        .HasColumnType("int");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("PedidoId")
                        .HasColumnType("int");

                    b.Property<int?>("ProfissionalId")
                        .HasColumnType("int");

                    b.Property<int>("StatusPagamentoId")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaPagamentoId");

                    b.HasIndex("ClienteId");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("FormaPagamentoId");

                    b.HasIndex("PedidoId");

                    b.HasIndex("ProfissionalId");

                    b.HasIndex("StatusPagamentoId");

                    b.ToTable("Pagamentos");
                });

            modelBuilder.Entity("wpf_projeto_integrador.Models.Pedido", b =>
                {
                    b.Property<int>("IdPedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPedido"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataPedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("Pendente");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdPedido");

                    b.HasIndex("ClienteId");

                    b.ToTable("Pedidos", (string)null);
                });

            modelBuilder.Entity("wpf_projeto_integrador.Models.Servico", b =>
                {
                    b.Property<int>("IdServico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdServico"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int?>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ProfissionalId")
                        .HasColumnType("int");

                    b.HasKey("IdServico");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("ProfissionalId");

                    b.ToTable("Servicos", null, t =>
                        {
                            t.HasCheckConstraint("CK_Servico_Prestador", "(\r\n                [EmpresaId] IS NOT NULL\r\n                AND [ProfissionalId] IS NULL\r\n              )\r\n              OR\r\n              (\r\n                [EmpresaId] IS NULL\r\n                AND [ProfissionalId] IS NOT NULL\r\n              )");
                        });
                });

            modelBuilder.Entity("wpf_projeto_integrador.Models.ServicoPedido", b =>
                {
                    b.Property<int>("IdItem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdItem"));

                    b.Property<string>("Observacao")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasDefaultValue("-");

                    b.Property<int>("PedidoId")
                        .HasColumnType("int");

                    b.Property<int>("ProfissionalId")
                        .HasColumnType("int");

                    b.Property<int>("ServicoId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("Pendente");

                    b.Property<decimal>("ValorServico")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdItem");

                    b.HasIndex("PedidoId");

                    b.HasIndex("ProfissionalId");

                    b.HasIndex("ServicoId");

                    b.ToTable("ServicosPedidos", (string)null);
                });

            modelBuilder.Entity("wpf_projeto_integrador.Models.StatusPagamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("StatusPagamentos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Pendente"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Pago"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Vencido"
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Cancelado"
                        });
                });

            modelBuilder.Entity("wpf_projeto_integrador.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NomeUsuario")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Telefone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("NomeUsuario")
                        .IsUnique();

                    b.ToTable("Usuarios", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("wpf_projeto_integrador.Models.Administrador", b =>
                {
                    b.HasBaseType("wpf_projeto_integrador.Models.Usuario");

                    b.Property<string>("NivelAcesso")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observacao")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Administradores", null, t =>
                        {
                            t.HasCheckConstraint("CK_Administrador_NivelAcesso", "NivelAcesso IN ('AdministradorGeral','Atendente','Suporte','Financeiro','Moderador')");
                        });
                });

            modelBuilder.Entity("wpf_projeto_integrador.Models.Cliente", b =>
                {
                    b.HasBaseType("wpf_projeto_integrador.Models.Usuario");

                    b.Property<string>("Bairro")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Cep")
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<string>("Cidade")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Estado")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Numero")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Rua")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.ToTable("Clientes", (string)null);
                });

            modelBuilder.Entity("wpf_projeto_integrador.Models.Empresa", b =>
                {
                    b.HasBaseType("wpf_projeto_integrador.Models.Usuario");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("nvarchar(18)");

                    b.Property<string>("Endereco")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NomeFantasia")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Responsavel")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasIndex("Cnpj")
                        .IsUnique()
                        .HasFilter("[Cnpj] IS NOT NULL");

                    b.ToTable("Empresas", (string)null);
                });

            modelBuilder.Entity("wpf_projeto_integrador.Models.Profissional", b =>
                {
                    b.HasBaseType("wpf_projeto_integrador.Models.Usuario");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int?>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<string>("Endereco")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Especialidade")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasIndex("EmpresaId");

                    b.ToTable("Profissionais", (string)null);
                });

            modelBuilder.Entity("wpf_projeto_integrador.Models.Avaliacao", b =>
                {
                    b.HasOne("wpf_projeto_integrador.Models.Cliente", "Cliente")
                        .WithMany("Avaliacoes")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("wpf_projeto_integrador.Models.ServicoPedido", "ServicoPedido")
                        .WithOne("Avaliacao")
                        .HasForeignKey("wpf_projeto_integrador.Models.Avaliacao", "ServicoPedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("ServicoPedido");
                });

            modelBuilder.Entity("wpf_projeto_integrador.Models.Chat", b =>
                {
                    b.HasOne("wpf_projeto_integrador.Models.Usuario", "Usuario1")
                        .WithMany()
                        .HasForeignKey("Usuario1Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("wpf_projeto_integrador.Models.Usuario", "Usuario2")
                        .WithMany()
                        .HasForeignKey("Usuario2Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario1");

                    b.Navigation("Usuario2");
                });

            modelBuilder.Entity("wpf_projeto_integrador.Models.LogSistema", b =>
                {
                    b.HasOne("wpf_projeto_integrador.Models.Usuario", "Usuario")
                        .WithMany("Logs")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("wpf_projeto_integrador.Models.Mensagem", b =>
                {
                    b.HasOne("wpf_projeto_integrador.Models.Chat", "Chat")
                        .WithMany("Mensagens")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("wpf_projeto_integrador.Models.Usuario", "Remetente")
                        .WithMany()
                        .HasForeignKey("RemetenteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Chat");

                    b.Navigation("Remetente");
                });

            modelBuilder.Entity("wpf_projeto_integrador.Models.Pagamento", b =>
                {
                    b.HasOne("wpf_projeto_integrador.Models.CategoriaPagamento", "CategoriaPagamento")
                        .WithMany("Pagamentos")
                        .HasForeignKey("CategoriaPagamentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("wpf_projeto_integrador.Models.Cliente", "Cliente")
                        .WithMany("Pagamentos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("wpf_projeto_integrador.Models.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId");

                    b.HasOne("wpf_projeto_integrador.Models.FormaPagamento", "FormaPagamento")
                        .WithMany("Pagamentos")
                        .HasForeignKey("FormaPagamentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("wpf_projeto_integrador.Models.Pedido", "Pedido")
                        .WithMany("Pagamentos")
                        .HasForeignKey("PedidoId");

                    b.HasOne("wpf_projeto_integrador.Models.Profissional", "Profissional")
                        .WithMany()
                        .HasForeignKey("ProfissionalId");

                    b.HasOne("wpf_projeto_integrador.Models.StatusPagamento", "StatusPagamento")
                        .WithMany("Pagamentos")
                        .HasForeignKey("StatusPagamentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CategoriaPagamento");

                    b.Navigation("Cliente");

                    b.Navigation("Empresa");

                    b.Navigation("FormaPagamento");

                    b.Navigation("Pedido");

                    b.Navigation("Profissional");

                    b.Navigation("StatusPagamento");
                });

            modelBuilder.Entity("wpf_projeto_integrador.Models.Pedido", b =>
                {
                    b.HasOne("wpf_projeto_integrador.Models.Cliente", "Cliente")
                        .WithMany("Pedidos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("wpf_projeto_integrador.Models.Servico", b =>
                {
                    b.HasOne("wpf_projeto_integrador.Models.Empresa", "Empresa")
                        .WithMany("Servicos")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("wpf_projeto_integrador.Models.Profissional", "Profissional")
                        .WithMany("Servicos")
                        .HasForeignKey("ProfissionalId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Empresa");

                    b.Navigation("Profissional");
                });

            modelBuilder.Entity("wpf_projeto_integrador.Models.ServicoPedido", b =>
                {
                    b.HasOne("wpf_projeto_integrador.Models.Pedido", "Pedido")
                        .WithMany("ServicosPedidos")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("wpf_projeto_integrador.Models.Profissional", "Profissional")
                        .WithMany("ServicosPedidos")
                        .HasForeignKey("ProfissionalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("wpf_projeto_integrador.Models.Servico", "Servico")
                        .WithMany("ServicosPedidos")
                        .HasForeignKey("ServicoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pedido");

                    b.Navigation("Profissional");

                    b.Navigation("Servico");
                });

            modelBuilder.Entity("wpf_projeto_integrador.Models.Administrador", b =>
                {
                    b.HasOne("wpf_projeto_integrador.Models.Usuario", null)
                        .WithOne()
                        .HasForeignKey("wpf_projeto_integrador.Models.Administrador", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("wpf_projeto_integrador.Models.Cliente", b =>
                {
                    b.HasOne("wpf_projeto_integrador.Models.Usuario", null)
                        .WithOne()
                        .HasForeignKey("wpf_projeto_integrador.Models.Cliente", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("wpf_projeto_integrador.Models.Empresa", b =>
                {
                    b.HasOne("wpf_projeto_integrador.Models.Usuario", null)
                        .WithOne()
                        .HasForeignKey("wpf_projeto_integrador.Models.Empresa", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("wpf_projeto_integrador.Models.Profissional", b =>
                {
                    b.HasOne("wpf_projeto_integrador.Models.Empresa", "Empresa")
                        .WithMany("Profissionais")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("wpf_projeto_integrador.Models.Usuario", null)
                        .WithOne()
                        .HasForeignKey("wpf_projeto_integrador.Models.Profissional", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("wpf_projeto_integrador.Models.CategoriaPagamento", b =>
                {
                    b.Navigation("Pagamentos");
                });

            modelBuilder.Entity("wpf_projeto_integrador.Models.Chat", b =>
                {
                    b.Navigation("Mensagens");
                });

            modelBuilder.Entity("wpf_projeto_integrador.Models.FormaPagamento", b =>
                {
                    b.Navigation("Pagamentos");
                });

            modelBuilder.Entity("wpf_projeto_integrador.Models.Pedido", b =>
                {
                    b.Navigation("Pagamentos");

                    b.Navigation("ServicosPedidos");
                });

            modelBuilder.Entity("wpf_projeto_integrador.Models.Servico", b =>
                {
                    b.Navigation("ServicosPedidos");
                });

            modelBuilder.Entity("wpf_projeto_integrador.Models.ServicoPedido", b =>
                {
                    b.Navigation("Avaliacao");
                });

            modelBuilder.Entity("wpf_projeto_integrador.Models.StatusPagamento", b =>
                {
                    b.Navigation("Pagamentos");
                });

            modelBuilder.Entity("wpf_projeto_integrador.Models.Usuario", b =>
                {
                    b.Navigation("Logs");
                });

            modelBuilder.Entity("wpf_projeto_integrador.Models.Cliente", b =>
                {
                    b.Navigation("Avaliacoes");

                    b.Navigation("Pagamentos");

                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("wpf_projeto_integrador.Models.Empresa", b =>
                {
                    b.Navigation("Profissionais");

                    b.Navigation("Servicos");
                });

            modelBuilder.Entity("wpf_projeto_integrador.Models.Profissional", b =>
                {
                    b.Navigation("Servicos");

                    b.Navigation("ServicosPedidos");
                });
#pragma warning restore 612, 618
        }
    }
}
